spring:
  application:
    name: cloud-feign1
  #zipkin 服务器地址
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
      sampler:
        percentage: 1
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
